# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitFaker < Formula
  desc ""
  homepage ""
  version "0.0.9"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "http://github.com/danieltaub96/git-faker/releases/download/v0.0.9/git-faker_0.0.9_darwin_amd64.tar.gz", :using => CurlDownloadStrategy.
      sha256 "5c088653033af851de31ed385747817e58d19a985c660519b31cb01e326ad305"
    end
    if Hardware::CPU.arm?
      url "http://github.com/danieltaub96/git-faker/releases/download/v0.0.9/git-faker_0.0.9_darwin_arm64.tar.gz", :using => CurlDownloadStrategy.
      sha256 "43179e37d2b835ebdc9b663ac2b7a5283b716622cc3ac65b1b895f5153d5aeee"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "http://github.com/danieltaub96/git-faker/releases/download/v0.0.9/git-faker_0.0.9_linux_amd64.tar.gz", :using => CurlDownloadStrategy.
      sha256 "86471a52bf6e48090601e4ddcb706ad979b0366d72dbddcb75654d876345724d"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "http://github.com/danieltaub96/git-faker/releases/download/v0.0.9/git-faker_0.0.9_linux_arm64.tar.gz", :using => CurlDownloadStrategy.
      sha256 "870d63f5a1927da5a10ee01eaa810f481c90761743c4f25658b7a3a97f4ca74d"
    end
  end

  depends_on "git"

  def install
    bin.install "git-faker"
  end
end
